/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Banner {
  'title' : string,
  'discountText' : string,
  'subtitle' : string,
}
export interface Category {
  'icon' : string,
  'name' : string,
  'description' : string,
}
export interface Product {
  'originalPrice' : [] | [bigint],
  'name' : string,
  'category' : string,
  'badge' : [] | [string],
  'price' : bigint,
}
export interface StoreInfo {
  'hours' : string,
  'tagline' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface _SERVICE {
  'getBanner' : ActorMethod<[string], Banner>,
  'getBanners' : ActorMethod<[], Array<Banner>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCategory' : ActorMethod<[string], Category>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getStoreInfo' : ActorMethod<[], StoreInfo>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];