/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Banner = IDL.Record({
  'title' : IDL.Text,
  'discountText' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const Category = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Product = IDL.Record({
  'originalPrice' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'category' : IDL.Text,
  'badge' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});
export const StoreInfo = IDL.Record({
  'hours' : IDL.Text,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getBanner' : IDL.Func([IDL.Text], [Banner], ['query']),
  'getBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCategory' : IDL.Func([IDL.Text], [Category], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getStoreInfo' : IDL.Func([], [StoreInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Banner = IDL.Record({
    'title' : IDL.Text,
    'discountText' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const Category = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Product = IDL.Record({
    'originalPrice' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'category' : IDL.Text,
    'badge' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  const StoreInfo = IDL.Record({
    'hours' : IDL.Text,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getBanner' : IDL.Func([IDL.Text], [Banner], ['query']),
    'getBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCategory' : IDL.Func([IDL.Text], [Category], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStoreInfo' : IDL.Func([], [StoreInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };